spring:
  datasource:
    url: jdbc:mariadb://i10a805.p.ssafy.io:3306/manitodb
    driver-class-name: org.mariadb.jdbc.Driver
    username: manito
    password: manito
#    url: jdbc:mysql://localhost:3306/manitodb?serverTimezone=UTC&characterEncoding=UTF-8
#    username: manito
#    password: manito
#    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    #        show_sql: true
#        format_sql: true
    open-in-view: false
#      generate-ddl: true
  data:
    redis:
      host: i10a805.p.ssafy.io
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: manito

